### ISSUE TITLE
Some basic documentation to CMlyst

### ISSUE THREAD

**Issue by c-cesar** [cutelyst/CMlyst#2]
I'm reading the code of the project to figure out their functionalities, but it would be really nice some documentation.
Wt, Tufão, TreeFrog, neither of them have a CMS, so I think CMlyst can be a strong advantage to Cutelyst.

**Comment by dantti** [comment]
Right, ATM, and REALLY ATM I'm doing a major rewrite of CMlyst, it will use sqlite instead of QSettings (which proved to be a bad option) and I'm trying to make Ghost themes usable with minimum changes.
I'll probably do another release of Cutelyst tomorrow due new features I'm using in CMlyst, so stay tunned, and if possible send patches :D
