### ISSUE TITLE
Admin General: Front page displays, A static page: Posts page: shows only Pages

### ISSUE THREAD

**Issue by Light-Wizzard** [cutelyst/CMlyst#9]
Admin General
Front page displays
A static page (select below)
Posts page:
This shows only Pages and not Post, its the same list as above for Front page.

**Comment by dantti** [comment]
This is not a bug, it's the way it works on WordPress, not very easy to get to at first.
The Posts page is a page that the content won't be used, only it's path.
For example, you create a Page named "All Posts" which URL is http://domain/all_our_posts, so that when it's reached it will list the posts.
